### PR TITLE
add instructions for steam deck desktop mode

### PR DESCRIPTION
**Pull request by zot**

### CODE REVIEW

**Review by wheaney — COMMENTED** [review]
This might be easier to maintain in [the wiki](https://github.com/wheaney/breezy-desktop/wiki)?

**Comment by zot** [comment]
Sure -- where's the wiki?

**Comment by wheaney** [comment]
Linked in my previous comment. Let me know if it's not allowing edits.

**Comment by zot** [comment]
Well derp!

-- Bill

**Pull request closed without merging**
